feat(Picker): add new style of Picker to support dividerColor
tuya/tuya-panel-kit pull request #74
Opened 2021-05-31 13:19 UTC by ZengBeauty

## Description

Add new style of Picker to support dividerColor in IOS.

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-06-02 09:56 UTC, youngjuning commented
1

2021-06-07 07:44 UTC, ShinyLeee commented on src/components/picker-view/TYRCTPicker.js
> +/* eslint-disable */
注意下 eslint

2021-06-07 08:01 UTC, ShinyLeee commented on src/components/picker-view/index.ios.js
> +  const appRnVersion = get(TYNative, 'mobileInfo.appRnVersion');
可采用 UIManager 里是否存在该组件判断更为准确

2021-06-07 08:27 UTC, ShinyLeee commented on src/components/picker-view/picker/index.ios.js
> +    fontFamily: PropTypes.string,
fontFamily 正常应该为有限的集合

2021-06-07 08:58 UTC, ShinyLeee commented on src/components/date-picker/datePicker.js
> +    let pickerFontSize = 30;
不需要 convertX ？

2021-06-07 09:00 UTC, ShinyLeee commented on src/components/picker-view/picker/index.ios.js
> +const TYRCTPicker = requireNativeComponent('TYRCTPicker');
requireNativeComponent 优化下，避免不支持的 app 环境崩溃

2021-06-07 09:01 UTC, ShinyLeee commented on src/components/picker-view/picker/index.ios.js
> +const TYRCTPicker = requireNativeComponent('TYRCTPicker');
https://stackoverflow.com/questions/48953434/check-if-native-ui-component-does-exist

2021-06-07 09:03 UTC, ShinyLeee commented on src/components/popup/picker.js
> +      pickerFontSize = 30;
convertX ?

2021-06-07 09:07 UTC, ShinyLeee commented on src/components/theme/base.js
> +    fontSize: 30,
是否有兼容问题，如果未启用新版本的 picker 却改大了字体大小

2021-06-07 09:08 UTC, ShinyLeee requested changes
评论的上述几个问题留意下

2021-06-07 11:30 UTC, ShinyLeee approved these changes

2021-06-07 11:36 UTC, ZengBeauty commented
@ShinyLeee ts typing https://github.com/tuya/DefinitelyTyped/commit/89d2f41f1f3f2f72fa62de2e9741b749b483cdb5

2021-06-08 09:16 UTC, youngjuning approved these changes
本地已验证，没有发现问题。

2021-06-08 09:16 UTC, merged