feat(SwitchButton): add new type && more style
tuya/tuya-panel-kit pull request #77
Opened 2021-06-02 10:57 UTC by ZengBeauty

## Description

Add some more Props && fit more style.

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-06-02 10:57 UTC, ZengBeauty commented
<img width="303" alt="企业微信20210602-182644@2x" src="https://user-images.githubusercontent.com/34674396/120468972-5e72d880-c3d4-11eb-892e-9ba3866165d6.png">

2021-06-03 01:20 UTC, ShinyLeee commented
@ZengBeauty 合并下 [#64](https://github.com/tuya/tuya-panel-kit/pull/64) example 多语言规划化

2021-06-07 09:10 UTC, ShinyLeee commented on src/components/switch-button/switch-button.js
> +    switchType: PropTypes.string,
可枚举值的类型

2021-06-07 09:11 UTC, ShinyLeee requested changes
附下 typing

2021-06-16 09:31 UTC, ZengBeauty commented
typing 详见 https://github.com/tuya/DefinitelyTyped/commit/a6803228d812a5dc663358d435a8dc262f1355a7

2021-06-22 02:04 UTC, ShinyLeee approved these changes

2021-06-22 06:54 UTC, ShinyLeee requested changes
单测覆盖率下降了 10%，新增的属性需覆盖全

2021-06-22 09:39 UTC, youngjuning requested changes
加一个小括号！

2021-06-22 09:39 UTC, youngjuning commented on example/src/i18n/strings.js
> -  },
@ZengBeauty 这里多删了一个小括号？

2021-06-22 09:51 UTC, merged