feat(tabbar): add new type of Tabbar
tuya/tuya-panel-kit pull request #78
Opened 2021-06-02 11:03 UTC by ZengBeauty

## Description

Tabbar add new type && fit more style.

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-06-02 11:03 UTC, ZengBeauty commented
<img width="303" alt="企业微信20210602-190138@2x" src="https://user-images.githubusercontent.com/34674396/120469686-43549880-c3d5-11eb-90ba-0ecb239a9098.png">

2021-06-07 09:25 UTC, ShinyLeee commented on src/components/tabbar/radio-button/group.js
> +    type: PropTypes.string,
可枚举的 type

2021-06-07 09:26 UTC, ShinyLeee requested changes
补下 typing

2021-06-16 09:31 UTC, ZengBeauty commented
typing 详见 https://github.com/tuya/DefinitelyTyped/commit/a6803228d812a5dc663358d435a8dc262f1355a7

2021-06-22 02:07 UTC, ShinyLeee approved these changes

2021-06-22 02:13 UTC, ShinyLeee commented
@ZengBeauty 合并下 commit，处理下 commit message，没有大驼峰，检查报错

2021-06-22 04:08 UTC, closed without merging