feat: add feature tuya-panel-mall-toolbar-indicator
tuya/tuya-panel-kit pull request #93
Opened 2021-07-22 03:54 UTC by Nfs-oh

## Description

add the feature tuya-panel-mall-toobar-indicator.

## Type of change

Please select the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-07-22 06:43 UTC, ShinyLeee commented on packages/tuya-panel-topbar-mall-indicator/src/index.tsx
> +  titlePress,
onTitlePress
onRightPress

语义更好一些

2021-07-22 06:43 UTC, ShinyLeee requested changes
补下单元测试

2021-07-27 03:50 UTC, ZengBeauty commented
yarn build 失败

2021-07-27 11:17 UTC, ShinyLeee commented on packages/tuya-panel-topbar-mall-indicator/src/index.tsx
> +        }}
借鉴下 TopBar 的实现，把剩余的 TopBar.Content props 传递进去，可拓展性高一些

2021-07-30 06:47 UTC, closed without merging

2021-07-30 06:48 UTC, Nfs-oh commented
the branch is so complement, so delete it add create a new branch